//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 04:27:10 PM ICT 
//


package xyz.un4ckn0wl3z.xsdgen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://tempuri.org/}CardStatusBankResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cardStatusBankResponse"
})
@XmlRootElement(name = "Body")
public class Body {

    @XmlElement(name = "CardStatusBankResponse", namespace = "http://tempuri.org/", required = true)
    protected CardStatusBankResponse cardStatusBankResponse;

    /**
     * Gets the value of the cardStatusBankResponse property.
     * 
     * @return
     *     possible object is
     *     {@link CardStatusBankResponse }
     *     
     */
    public CardStatusBankResponse getCardStatusBankResponse() {
        return cardStatusBankResponse;
    }

    /**
     * Sets the value of the cardStatusBankResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardStatusBankResponse }
     *     
     */
    public void setCardStatusBankResponse(CardStatusBankResponse value) {
        this.cardStatusBankResponse = value;
    }

	@Override
	public String toString() {
		return "Body [cardStatusBankResponse=" + cardStatusBankResponse + "]";
	}

    
    
}
